version: '3'
services:
  db:
    image: postgres:9.4.18
    container_name: apm_db_sit
    hostname: sit_db
    restart: always
    ports:
      - "54322:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ge_apm:/var/lib/postgresql/data
      - /home/nick/data:/home/nick/data

networks:
  backend:
    
volumes:
  ge_apm:

